<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_ThongTinUser</name>
   <tag></tag>
   <elementGuidId>179a95d1-8210-46b7-b1d5-e5d15005546b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.navbar-nav.mr-0.ml-2 > li.nav-item.dropdown.mr-2 > div.dropdown-menu > a.dropdown-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarSupportedContent']/ul[2]/li/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>448486fe-82ae-44dd-9749-b9adf1fe1737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://truyenteen.me/userinfo/45</value>
      <webElementGuid>9786a20d-7ec6-4361-9ca9-b3429de75b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>066849fc-56df-4502-bf30-1a8f5eeb6faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Thông tin user</value>
      <webElementGuid>b99e8596-3611-4619-b286-6ecf2e0925ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarSupportedContent&quot;)/ul[@class=&quot;navbar-nav mr-0 ml-2&quot;]/li[@class=&quot;nav-item dropdown mr-2&quot;]/div[@class=&quot;dropdown-menu&quot;]/a[@class=&quot;dropdown-item&quot;]</value>
      <webElementGuid>c4b97a5d-c83f-44fb-9269-b0cd86d7a510</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarSupportedContent']/ul[2]/li/div/a</value>
      <webElementGuid>e319ce3b-258f-40f1-9bdb-c3ecf3e8b9c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Thông tin user')]</value>
      <webElementGuid>0bd116a2-5658-45c7-85b5-79fe3950a0fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='letatanhtuan'])[1]/following::a[1]</value>
      <webElementGuid>84c250cb-bf0a-49a6-a01d-f6ee1de9587e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tối'])[1]/following::a[2]</value>
      <webElementGuid>6a849b51-d202-4ef4-bb73-dd08e3668ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Truyện đề cử'])[1]/preceding::a[6]</value>
      <webElementGuid>811644d9-72fc-4b1b-9fa2-52cd6c58065d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thông tin user']/parent::*</value>
      <webElementGuid>7033a0de-57b3-4b6e-8d74-363b798217b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://truyenteen.me/userinfo/45')]</value>
      <webElementGuid>0a6beb25-e71d-40ff-8d45-b4ae2559a94c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li/div/a</value>
      <webElementGuid>f77c723b-6cc0-4cfb-b2b3-c1df76934db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://truyenteen.me/userinfo/45' and (text() = ' Thông tin user' or . = ' Thông tin user')]</value>
      <webElementGuid>c6cf44fd-f18c-486b-b862-03382d054608</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
