<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_TruyenTeen</name>
   <tag></tag>
   <elementGuidId>7e86bbaf-2bbb-487f-88b8-b54b2b1f7efb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.navbar-brand.text-white</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'TruyenTeen')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3c3d170a-3485-43c0-b43b-93e96b18db32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navbar-brand text-white</value>
      <webElementGuid>887d949c-3e3b-4f00-81ea-bbc25ce97359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://truyenteen.me</value>
      <webElementGuid>c6af6c04-f244-4a70-9dce-81080b28e9f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TruyenTeen</value>
      <webElementGuid>c015664e-b9e4-4f01-afcb-2e311d4e6b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/header[@class=&quot;site-navbar js-sticky-header site-navbar-target sticky-top&quot;]/nav[@class=&quot;navbar navbar-expand-lg navbar-light&quot;]/div[@class=&quot;container&quot;]/a[@class=&quot;navbar-brand text-white&quot;]</value>
      <webElementGuid>a585d75e-0f7d-4ac9-b5a4-a76f8c0a1a76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'TruyenTeen')]</value>
      <webElementGuid>6bf8f0e9-4845-4a1e-a5e7-9d65cfb7d57c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bách Hợp'])[1]/preceding::a[2]</value>
      <webElementGuid>9c5ac1cb-53b4-4518-873e-18c548a9727d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cổ Đại'])[1]/preceding::a[3]</value>
      <webElementGuid>e2f273f2-bbca-4814-8815-7bd747408bf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TruyenTeen']/parent::*</value>
      <webElementGuid>0ffab68c-8f30-4bfd-a1d1-d609f835cb49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://truyenteen.me')]</value>
      <webElementGuid>9fed8b77-8ecc-4017-a6b4-e17d31e7f5be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>ee03c377-1034-4e10-9a77-3cfca1dbd4a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://truyenteen.me' and (text() = 'TruyenTeen' or . = 'TruyenTeen')]</value>
      <webElementGuid>cdf6f670-2ddf-4426-82dd-4bd0a5ebade4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
